tokens:
    telegram: "5328375124:AAGKHa7X3iF1azoFrCAxh9e31Rm8tIG9MW8" # @redempt_test_2_bot
bots:
    Watcher:
        number: "9104499982"
    Oleg:
        number: "9104499982"
    Einstein:
        number: "9104499982"
    Boulevard Depo:
        number: "9104499982"
