tokens:
    telegram: "5365372574:AAEb_edpfgvf-qdZCXf3syrlziIwHSv2fUg"
bots:
    Watcher:
        number: "9104499982"
    Oleg:
        number: "9104499982"
    Einstein:
        number: "9104499982"
    Boulevard Depo:
        number: "9104499982"
